name:                abides
version:             0.0.1
github:              "athanclark/abides"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2019 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Simple boolean tests to see if a value abides by certain properties
category:            Data, Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/abides#readme>

dependencies:
- base >= 4.7 && < 5
- comonad

library:
  source-dirs: src

tests:
  abides-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - abides
    - tasty
    - tasty-quickcheck
